name: Bug report
description: Create a report to help us improve
labels: ["NeedsInvestigation", "Triage"]
body:
  - type: textarea
    id: version
    attributes:
      label: helm2cue version
      description: What version of helm2cue are you using? Paste the output of `helm2cue version`.
      placeholder: |
        helm2cue (devel)
        go go1.24.0
        commit abc1234...
    validations:
      required: true
  - type: textarea
    id: helm-version
    attributes:
      label: Helm version
      description: If using the `chart` subcommand, what version of Helm are you using? Paste the output of `helm version`. Not required for `template` subcommand issues.
      placeholder: |
        version.BuildInfo{Version:"v4.1.1", ...}
    validations:
      required: false
  - type: dropdown
    id: latest
    attributes:
      label: Does this issue reproduce with the latest release?
      options:
        - "Yes"
        - "No"
        - Not sure
    validations:
      required: true
  - type: textarea
    id: what-did-you-do
    attributes:
      label: What did you do?
      description: |
        Provide a recipe for reproducing the error. Include the template input and the command you ran.

        For `chart` subcommand issues: please confirm that `helm template` succeeds on your chart before filing. helm2cue only supports charts that Helm itself can render.
      placeholder: |
        For chart issues:
        1. `helm template my-release ./my-chart` succeeds with Helm vX.Y.Z
        2. Ran `helm2cue chart ./my-chart ./output`
        3. ...

        For template issues:
        1. Created a template file with ...
        2. Ran `helm2cue template my-template.yaml`
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What did you see instead?
    validations:
      required: true
